apiVersion: v2
name: gradio-llm-rag
description: A Helm chart for Gradio LLM RAG application with PostgreSQL vector database
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - gradio
  - llm
  - rag
  - postgresql
  - vector-database
home: https://github.com/your-org/llm-rag-deployment
sources:
  - https://github.com/your-org/llm-rag-deployment
maintainers:
  - name: Your Name
    email: your.email@example.com 