{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "gradio-llm-rag.fullname" . }}-route
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "gradio-llm-rag.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.argocd.syncWave }}"
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "gradio-llm-rag.fullname" . }}-service
    weight: 100
  port:
    targetPort: http
  {{- if .Values.route.tls }}
  tls:
    termination: {{ .Values.route.tls.termination }}
  {{- end }}
  wildcardPolicy: {{ .Values.route.wildcardPolicy }}
{{- end }} 